var expressCompanys=[
{ "code": "ems", "name": "EMS快递" },
{ "code": "shentong", "name": "申通快递" },
{ "code": "shunfeng", "name": "顺丰快递" },
{ "code": "yuantong", "name": "圆通快递" },
{ "code": "yunda", "name": "韵达快递" },
{ "code": "huitong", "name": "百世汇通快递" },
{ "code": "tiantian", "name": "天天快递" },
{ "code": "zhongtong", "name": "中通快递" },
{ "code": "zhaijisong", "name": "宅急送快递" },
{ "code": "pingyou", "name": "中国邮政" },
{ "code": "quanfeng", "name": "全峰快递" },
{ "code": "guotong", "name": "国通快递" },
{ "code": "jingdong", "name": "京东快递" },
{ "code": "sure", "name": "速尔快递" },
{ "code": "kuaijie", "name": "快捷快递" },
{ "code": "ririshun", "name": "日日顺物流" },
{ "code": "zhongtie", "name": "中铁快运" },
{ "code": "yousu", "name": "优速快递" },
{ "code": "longbang", "name": "龙邦快递" },
{ "code": "debang", "name": "德邦物流" },
{ "code": "rufeng", "name": "如风达快递" },
{ "code": "lianhaotong", "name": "联昊通快递" },
{ "code": "fedex", "name": "国际Fedex" },
{ "code": "fedexcn", "name": "Fedex国内" },
{ "code": "dhl", "name": "DHL快递" },
{ "code": "xinfeng", "name": "信丰快递" },
{ "code": "eyoubao", "name": "E邮宝" },
{ "code": "zhongxinda", "name": "忠信达快递" },
{ "code": "changtong", "name": "长通物流" },
{ "code": "usps", "name": "USPS快递" },
{ "code": "huaqi", "name": "华企快递" },
{ "code": "zhima", "name": "芝麻开门快递" },
{ "code": "gnxb", "name": "邮政小包" },
{ "code": "nell", "name": "尼尔快递" },
{ "code": "zengyi", "name": "增益快递" },
{ "code": "yuxin", "name": "宇鑫物流" },
{ "code": "xingchengzhaipei", "name": "星程宅配快递" },
{ "code": "anneng", "name": "安能物流" },
{ "code": "dada", "name": "大达物流" },
{ "code": "tongzhishu", "name": "高考录取通知书" },
{ "code": "aol", "name": "AOL快递" },
{ "code": "dongjun", "name": "成都东骏快递" },
{ "code": "suning", "name": "苏宁快递" },
{ "code": "upu", "name": "UPU-Universal Postal Union" },
{ "code": "quanyi", "name": "全一快递" },
{ "code": "huayu", "name": "华宇物流" },
{ "code": "quanritong", "name": "全日通快递" },
{ "code": "fengcheng", "name": "丰程物流" },
{ "code": "ane66", "name": "安能小包" },
{ "code": "800best", "name": "百世快运" },
{ "code": "minhang", "name": "民航快递" },
{ "code": "zhongyou", "name": "中邮物流" },
{ "code": "jiaji", "name": "佳吉快运" },
{ "code": "wanxiang", "name": "万象物流" },
{ "code": "beihai", "name": "贝海国际快递" },
{ "code": "junfeng", "name": "墨尔本骏丰快递" },
{ "code": "junda", "name": "骏达快递" },
{ "code": "quanxintong", "name": "全信通快递" },
{ "code": "ups", "name": "UPS快递" },
{ "code": "tnt", "name": "TNT快递" },
{ "code": "yibang", "name": "一邦快递" },
{ "code": "shenghui", "name": "盛辉物流" },
{ "code": "yafeng", "name": "亚风快递" },
{ "code": "dsu", "name": "D速快递" },
{ "code": "datian", "name": "大田物流" },
{ "code": "jiayi", "name": "佳怡物流" },
{ "code": "jiayunmei", "name": "加运美快递" },
{ "code": "quanchen", "name": "全晨快递" },
{ "code": "ocs", "name": "OCS快递" },
{ "code": "shengfeng", "name": "盛丰物流" },
{ "code": "xinbang", "name": "新邦物流" },
{ "code": "chengguang", "name": "程光快递" },
{ "code": "fengda", "name": "丰达快递" },
{ "code": "feihang", "name": "原飞航物流" },
{ "code": "jinyue", "name": "晋越快递" },
{ "code": "yuefeng", "name": "越丰快递" },
{ "code": "anjie", "name": "安捷快递" },
{ "code": "aae", "name": "AAE快递" },
{ "code": "yuntong", "name": "运通中港快递" },
{ "code": "dpex", "name": "DPEX快递" },
{ "code": "yuancheng", "name": "远成物流" },
{ "code": "gdyz", "name": "广东邮政物流" },
{ "code": "aramex", "name": "Aramex国际快递" },
{ "code": "intmail", "name": "国际邮政快递" },
{ "code": "ytfh", "name": "北京一统飞鸿快递" },
{ "code": "lejiedi", "name": "乐捷递快递" },
{ "code": "santai", "name": "三态速递" },
{ "code": "chuanzhi", "name": "传志快递" },
{ "code": "gongsuda", "name": "共速达物流|快递" },
{ "code": "ees", "name": "百福东方物流" },
{ "code": "scs", "name": "伟邦(SCS)快递" },
{ "code": "pinganda", "name": "平安达" },
{ "code": "yad", "name": "源安达快递" },
{ "code": "disifang", "name": "递四方速递" },
{ "code": "yinjie", "name": "顺捷丰达快递" },
{ "code": "jldt", "name": "嘉里大通物流" },
{ "code": "coe", "name": "东方快递" },
{ "code": "chuanxi", "name": "传喜快递" },
{ "code": "feibao", "name": "飞豹快递" },
{ "code": "jingguang", "name": "京广快递" },
{ "code": "feiyuan", "name": "飞远物流" },
{ "code": "cszx", "name": "城市之星" },
{ "code": "rpx", "name": "RPX保时达" },
{ "code": "citylink", "name": "CityLinkExpress" },
{ "code": "chengshi100", "name": "城市100" },
{ "code": "lijisong", "name": "成都立即送快递" },
{ "code": "balunzhi", "name": "巴伦支" },
{ "code": "dayang", "name": "大洋物流快递" },
{ "code": "diantong", "name": "店通快递" },
{ "code": "fanyu", "name": "凡宇快递" },
{ "code": "haosheng", "name": "昊盛物流" },
{ "code": "hebeijianhua", "name": "河北建华快递" },
{ "code": "jixianda", "name": "急先达物流" },
{ "code": "suijia", "name": "穗佳物流" },
{ "code": "shengan", "name": "圣安物流" },
{ "code": "saiaodi", "name": "赛澳递" },
{ "code": "haihong", "name": "山东海红快递" },
{ "code": "weitepai", "name": "微特派" },
{ "code": "chengji", "name": "城际快递" },
{ "code": "fardar", "name": "Fardar" },
{ "code": "henglu", "name": "恒路物流" },
{ "code": "hwhq", "name": "海外环球快递" },
{ "code": "jinda", "name": "金大物流" },
{ "code": "kuayue", "name": "跨越速运" },
{ "code": "kcs", "name": "顺鑫(KCS)快递" },
{ "code": "mingliang", "name": "明亮物流" },
{ "code": "minbang", "name": "民邦快递" },
{ "code": "minsheng", "name": "闽盛快递" },
{ "code": "xiyoute", "name": "希优特快递" },
{ "code": "xianglong", "name": "祥龙运通快递" },
{ "code": "yishunhang", "name": "亿顺航快递" },
{ "code": "benteng", "name": "成都奔腾国际快递" },
{ "code": "zhongtian", "name": "济南中天万运" },
{ "code": "zhengzhoujianhua", "name": "郑州建华快递" },
{ "code": "feite", "name": "飞特物流" },
{ "code": "huahan", "name": "华翰物流" },
{ "code": "baotongda", "name": "宝通达" },
{ "code": "chukouyi", "name": "出口易物流" },
{ "code": "yumeijie", "name": "誉美捷快递" },
{ "code": "kuanrong", "name": "宽容物流" },
{ "code": "nanbei", "name": "南北快递" },
{ "code": "wanbo", "name": "万博快递" },
{ "code": "suchengzhaipei", "name": "速呈宅配" },
{ "code": "shengbang", "name": "晟邦物流" },
{ "code": "baiqian", "name": "百千诚国际物流" },
{ "code": "gaotie", "name": "高铁快递" },
{ "code": "guanda", "name": "冠达快递" },
{ "code": "haolaiyun", "name": "好来运快递" },
{ "code": "hutong", "name": "户通物流" },
{ "code": "huahang", "name": "华航快递" },
{ "code": "huangmajia", "name": "黄马甲快递" },
{ "code": "ucs", "name": "合众速递" },
{ "code": "jiete", "name": "捷特快递" },
{ "code": "jiuyi", "name": "久易快递" },
{ "code": "kuaiyouda", "name": "快优达速递" },
{ "code": "lanhu", "name": "蓝弧快递" },
{ "code": "menduimen", "name": "门对门快递" },
{ "code": "peixing", "name": "陪行物流" },
{ "code": "riyu", "name": "日昱物流" },
{ "code": "lindao", "name": "上海林道货运" },
{ "code": "shiyun", "name": "世运快递" },
{ "code": "aoshuo", "name": "奥硕物流" },
{ "code": "nsf", "name": "新顺丰（NSF）快递" },
{ "code": "dajin", "name": "大金物流" },
{ "code": "coscon", "name": "中国远洋运输(COSCON)" },
{ "code": "yuhong", "name": "宇宏物流" },
{ "code": "jiayu", "name": "佳宇物流" },
{ "code": "gangkuai", "name": "港快速递" },
{ "code": "kuaitao", "name": "快淘速递" },
{ "code": "sutong", "name": "速通物流" },
{ "code": "anxun", "name": "安迅物流" },
{ "code": "hkpost", "name": "香港邮政" },
{ "code": "jppost", "name": "日本邮政" },
{ "code": "singpost", "name": "新加坡邮政(Sing Post)" },
{ "code": "ztwl", "name": "中铁物流" },
{ "code": "ppbyb", "name": "贝邮宝" },
{ "code": "yanwen", "name": "燕文物流" },
{ "code": "feiyang", "name": "飞洋快递" },
{ "code": "zuochuan", "name": "佐川急便" },
{ "code": "hengyu", "name": "恒宇运通" },
{ "code": "mengsu", "name": "蒙速快递" },
{ "code": "wuhuan", "name": "五环速递" },
{ "code": "simai", "name": "思迈快递" },
{ "code": "jiahuier", "name": "佳惠尔快递" },
{ "code": "ande", "name": "安得物流" },
{ "code": "rongqing", "name": "荣庆物流" },
{ "code": "dashun", "name": "大顺物流" },
{ "code": "fangfangda", "name": "方方达物流" },
{ "code": "huiwen", "name": "汇文快递" },
{ "code": "sujie", "name": "速捷快递" },
{ "code": "dhlde", "name": "德国DHL快递" },
{ "code": "baiteng", "name": "百腾物流" },
{ "code": "dcs", "name": "DCS快递" },
{ "code": "dpd", "name": "DPD快递" },
{ "code": "tengxunda", "name": "腾迅达物流" },
{ "code": "pinjun", "name": "品骏快递" },
{ "code": "bse", "name": "蓝天快递" },
{ "code": "ueq", "name": "UEQ快递" },
{ "code": "xru", "name": "XRU快递" },
{ "code": "ycky", "name": "远成快运" },
{ "code": "anpost", "name": "爱尔兰邮政(AN POST)" },
{ "code": "koreapost", "name": "韩国邮政" },
{ "code": "posten", "name": "挪威邮政" },
{ "code": "auspost", "name": "澳大利亚邮政" },
{ "code": "posteit", "name": "意大利邮政" },
{ "code": "nzpost", "name": "新西兰邮政(NZPost)" },
{ "code": "bpost", "name": "比利时邮政(BPost)" },
{ "code": "depost", "name": "德国邮政(Deutsche Post)" },
{ "code": "correos", "name": "西班牙邮政" },
{ "code": "postnl", "name": "荷兰邮政" },
{ "code": "thailand", "name": "泰国邮政" },
{ "code": "bjems", "name": "北京邮政快递" },
{ "code": "canpost", "name": "加拿大邮政" },
{ "code": "postdanmark", "name": "丹麦邮政" },
{ "code": "ruston", "name": "俄速通快递" },
{ "code": "pochta", "name": "俄罗斯邮政" },
{ "code": "ukrposhta", "name": "乌克兰邮政" },
{ "code": "posmy", "name": "马来西亚邮政" },
{ "code": "postifi", "name": "芬兰邮政" },
{ "code": "indiapost", "name": "印度邮政" },
{ "code": "pocztex", "name": "波兰邮政" },
{ "code": "fanjie", "name": "泛捷国际快递" },
{ "code": "8dt", "name": "八达通快递" },
{ "code": "yikeman", "name": "易客满快递" },
{ "code": "fastgo", "name": "速派快递" },
{ "code": "cnpex", "name": "中邮快递" },
{ "code": "auexpress", "name": "澳邮中国快运" },
{ "code": "pca", "name": "PCA Express" },
{ "code": "adp", "name": "韩国ADP快递" },
{ "code": "a2u", "name": "A2U快递" },
{ "code": "birdex", "name": "笨鸟快递" },
{ "code": "omniva", "name": "爱沙尼亚邮政" },
{ "code": "laposte", "name": "突尼斯邮政" },
{ "code": "swisspost", "name": "瑞士邮政" },
{ "code": "ada", "name": "明大快递" },
{ "code": "stous", "name": "美国申通快递" },
{ "code": "quantium", "name": "Quantium" },
{ "code": "ontrac", "name": "OnTrac快递" },
{ "code": "eltacourier", "name": "希腊邮政" },
{ "code": "quantong", "name": "全通快递" },
{ "code": "tntuk", "name": "TNT UK" },
{ "code": "ajexpress", "name": "捷记方舟快递" },
{ "code": "jcex", "name": "佳成国际快递" },
{ "code": "ctt", "name": "葡萄牙邮政" },
{ "code": "gls", "name": "GLS快递" },
{ "code": "gaticn", "name": "GATI快递" },
{ "code": "southafricanpost", "name": "南非邮政" },
{ "code": "gatikwe", "name": "Gati-KWE快递" },
{ "code": "gsm", "name": "GSM快递" },
{ "code": "iparcel", "name": "UPS i-parcel" },
{ "code": "brazilcorreios", "name": "巴西邮政" },
{ "code": "saudipost", "name": "沙特邮政" },
{ "code": "cambodiapost", "name": "柬埔寨邮政_Cambodia Post" },
{ "code": "vnpost", "name": "越南邮政_Vietnam Post" },
{ "code": "chronopost-portugal", "name": "Chronopost Portugal" },
{ "code": "buylogic", "name": "捷买送(Buy Logic)快递" },
{ "code": "taiwan-post", "name": "台湾邮政(Taiwan Post)" },
{ "code": "speedpost", "name": "Speed Post" },
{ "code": "laopost", "name": "老挝邮政" },
{ "code": "emirates-post", "name": "阿联酋邮政(Emirates Post)" },
{ "code": "cuckoo", "name": "Cuckoo布谷鸟快递" },
{ "code": "dhl-global-mail", "name": "DHL eCommerce" },
{ "code": "asendia-usa", "name": "Asendia USA" },
{ "code": "yamato-japan", "name": "日本黑猫宅急便(Yamato Japan)" },
{ "code": "china-post", "name": "China Post" },
{ "code": "royal-mail", "name": "英国皇家邮政(Royal Mail)" },
{ "code": "parcel-force", "name": "Parcel Force" },
{ "code": "dpd-ireland", "name": "DPD Ireland" },
{ "code": "dpd-de", "name": "DPD Germany" },
{ "code": "czech-post", "name": "捷克邮政(Czech Post - Česká pošta)" },
{ "code": "gofly", "name": "Go Fly" },
{ "code": "chronopost-france", "name": "Chronopost France" },
{ "code": "laposte-france", "name": "法国邮政(La Poste)" },
{ "code": "correos-chile", "name": "智利邮政(Correos Chile)" },
{ "code": "jc56", "name": "锦程国际物流" },
{ "code": "posta-romana", "name": "罗马尼亚邮政(Poșta Română)" },
{ "code": "belpost", "name": "白俄罗斯邮政(Belpost)" },
{ "code": "ptt-posta", "name": "土耳其邮政(PTT Posta)" },
{ "code": "bgpost", "name": "保加利亚邮政(Bulgarian Posts)" },
{ "code": "iceland-post", "name": "冰岛邮政(Iceland Post)" },
{ "code": "lietuvos-pastas", "name": "立陶宛邮政(Lietuvos Paštas)" },
{ "code": "cyprus-post", "name": "塞浦路斯邮政(Cyprus Post)" },
{ "code": "magyar-posta", "name": "匈牙利邮政(Magyar Posta)" },
{ "code": "hrvatska-posta", "name": "克罗地亚邮政(Hrvatska Pošta)" },
{ "code": "postnord", "name": "瑞典邮政(PostNord)" },
{ "code": "macau-post", "name": "澳门邮政" },
{ "code": "israel-post", "name": "以色列邮政(Israel Post)" },
{ "code": "correo-argentino", "name": "阿根廷邮政(Correo Argentino)" },
{ "code": "nigeria-post", "name": "尼日利亚邮政(NiPost)" },
{ "code": "pakistan-post", "name": "巴基斯坦邮政(Pakistan Post)" },
{ "code": "latvijas-pasts", "name": "拉脱维亚邮政(Latvijas Pasts)" },
{ "code": "q-post", "name": "卡塔尔邮政(Q Post)" },
{ "code": "pos-indonesia-int", "name": "印度尼西亚邮政(Pos Indonesia)" },
{ "code": "afghan-post", "name": "阿富汗邮政(Afghan Post)" },
{ "code": "nova-poshta", "name": "Nova Poshta" },
{ "code": "liban-post", "name": "黎巴嫩邮政(Liban Post)" },
{ "code": "post-serbia", "name": "塞尔维亚邮政(POŠTA SRBIJE)" },
{ "code": "iran-post", "name": "伊朗邮政(Iran Post)" },
{ "code": "slovenska-posta", "name": "斯洛伐克邮政(Slovenská pošta)" },
{ "code": "tianfeng", "name": "天峰国际物流" },
{ "code": "one-world", "name": "One World 物流" },
{ "code": "yunexpress", "name": "云途物流" },
{ "code": "bangladesh-post", "name": "孟加拉国邮政(Bangladesh Post)" },
{ "code": "uk-mail", "name": "UK MAIL" },
{ "code": "skynet", "name": "Sky Net" },
{ "code": "colissimo", "name": "法国Colissimo" },
{ "code": "phlpost", "name": "菲律宾邮政（Philippine Post）" },
{ "code": "egypt-post", "name": "埃及邮政(Egypt Post)" },
{ "code": "fastway-nz", "name": "新西兰Fast Way 快递" },
{ "code": "fastway-au", "name": "澳大利亚Fast Way 快递" },
{ "code": "courierpost", "name": "新西兰CourierPost快递" },
{ "code": "fastway-ie", "name": "爱尔兰Fastway快递" },
{ "code": "austrian-post", "name": "奥地利邮政(Austrian Post)" },
{ "code": "sufengda", "name": "速丰达快递" },
{ "code": "qexpress", "name": "易达通快递" },
{ "code": "cfe", "name": "CFE 超峰快递" },
{ "code": "yisu", "name": "翼速物流" },
{ "code": "suyi", "name": "速翼快递" },
{ "code": "suchi", "name": "苏驰物流" },
{ "code": "shunda", "name": "顺达快递" },
{ "code": "arkexpress", "name": "方舟快递" },
{ "code": "fox", "name": "FOX快递" },
{ "code": "apeexpress", "name": "美速达快递" },
{ "code": "zhaosuda", "name": "兆速达物流" },
{ "code": "ushipshop", "name": "优寄快递" },
{ "code": "yixiang", "name": "亿翔快递" },
{ "code": "feiying", "name": "飞鹰物流" },
{ "code": "post-luxembourg", "name": "卢森堡邮政(Post Luxembourg)" },
{ "code": "maltapost", "name": "马耳他邮政(Malta Post)" },
{ "code": "correo-uruguayo", "name": "乌拉圭邮政(Correo Uruguayo)" },
{ "code": "poslaju", "name": "Pos Laju" },
{ "code": "tanzania-post", "name": "坦桑尼亚邮政(TANZANIA POSTA)" },
{ "code": "bermuda-post", "name": "百慕大邮政(Bermuda post)" },
{ "code": "peru-post", "name": "秘鲁邮政(Peru Post)" },
{ "code": "venezuela-post", "name": "委内瑞拉邮政" },
{ "code": "colombia-post", "name": "哥伦比亚邮政" },
{ "code": "correos-mexico", "name": "墨西哥邮政" },
{ "code": "albania-post", "name": "阿尔巴尼亚邮政" },
{ "code": "antilles-post", "name": "荷属安的列斯邮政" },
{ "code": "armenia-post", "name": "亚美尼亚邮政" },
{ "code": "ecuador-post", "name": "厄瓜多尔邮政" },
{ "code": "rwanda-post", "name": "卢旺达邮政" },
{ "code": "aruba-post", "name": "阿鲁巴邮政" },
{ "code": "el-salvador-post", "name": "萨尔瓦多邮政" },
{ "code": "senegal-post", "name": "塞内加尔邮政" },
{ "code": "macedonia-post", "name": "马其顿邮政" },
{ "code": "ethiopia-post", "name": "埃塞俄比亚邮政" },
{ "code": "madagascar-post", "name": "马达加斯加邮政" },
{ "code": "azerbaijan-post", "name": "阿塞拜疆邮政" },
{ "code": "maldives-post", "name": "马尔代夫邮政" },
{ "code": "slovenia-post", "name": "斯洛文尼亚邮政" },
{ "code": "bahamas-post", "name": "巴哈马邮政" },
{ "code": "mali-post", "name": "马里邮政" },
{ "code": "solomon-islands-post", "name": "所罗门群岛邮政" },
{ "code": "barbados-post", "name": "巴巴多斯邮政" },
{ "code": "gabon-post", "name": "加蓬邮政" },
{ "code": "georgia-post", "name": "格鲁吉亚邮政" },
{ "code": "mauritania-post", "name": "毛里塔尼亚邮政" },
{ "code": "mauritius-post", "name": "毛里求斯邮政" },
{ "code": "benin-post", "name": "贝宁邮政" },
{ "code": "ghana-post", "name": "加纳邮政" },
{ "code": "moldova-post", "name": "摩尔多瓦邮政" },
{ "code": "bhutan-post", "name": "不丹邮政" },
{ "code": "mongolia-post", "name": "蒙古邮政" },
{ "code": "bosnia-herzegovina-post", "name": "波黑邮政" },
{ "code": "guyana-post", "name": "圭亚那邮政" },
{ "code": "montenegro-post", "name": "黑山邮政" },
{ "code": "botswana-post", "name": "博茨瓦纳邮政" },
{ "code": "mozambique-post", "name": "莫桑比克邮政" },
{ "code": "myanmar-post", "name": "缅甸邮政" },
{ "code": "uganda-post", "name": "乌干达邮政" },
{ "code": "nepal-post", "name": "尼泊尔邮政" },
{ "code": "cayman-islands-post", "name": "开曼群岛邮政" },
{ "code": "uzbekistan-post", "name": "乌兹别克斯坦邮政" },
{ "code": "ivory-coast-post", "name": "科特迪瓦邮政" },
{ "code": "papua-new-guinea-post", "name": "巴布亚新几内亚邮政" },
{ "code": "vanuatu-post", "name": "瓦努阿图邮政" },
{ "code": "jamaica-post", "name": "牙买加邮政" },
{ "code": "paraguay-post", "name": "巴拉圭邮政" },
{ "code": "costa-rica-post", "name": "哥斯达黎加邮政" },
{ "code": "jordan-post", "name": "约旦邮政" },
{ "code": "zambia-post", "name": "赞比亚邮政" },
{ "code": "cuba-post", "name": "古巴邮政" },
{ "code": "kazakhstan-post", "name": "哈萨克斯坦邮政" },
{ "code": "zimbabwe-post", "name": "津巴布韦邮政" },
{ "code": "kenya-post", "name": "肯尼亚邮政" },
{ "code": "morocco-post", "name": "摩洛哥邮政" },
{ "code": "brunei-post", "name": "文莱邮政" },
{ "code": "dominican-post", "name": "多米尼加邮政(INPOSDOM)" },
{ "code": "anlexpress", "name": "新干线快递" },
{ "code": "expressplus", "name": "澳洲新干线快递" },
{ "code": "ewe", "name": "EWE快递" },
{ "code": "zhunshi", "name": "准实快递" },
{ "code": "jgwl", "name": "景光物流" },
{ "code": "qq-ex", "name": "QQ-EX快递" },
{ "code": "srilanka-post", "name": "斯里兰卡邮政" },
{ "code": "fengtong", "name": "丰通快运" },
{ "code": "duoduo", "name": "多多快运" },
{ "code": "zhixing", "name": "志行物流" },
{ "code": "chengzhong", "name": "诚中物流" },
{ "code": "happylink", "name": "HappyLink快递" },
{ "code": "360zebra", "name": "斑马物联网" },
{ "code": "ezhuanyun", "name": "易转运" },
{ "code": "jixiangyou", "name": "吉祥邮" },
{ "code": "easytocn", "name": "运淘美国" },
{ "code": "shlexp", "name": "畅灵国际物流" },
{ "code": "hermes", "name": "Hermes快递" },
{ "code": "postelbe", "name": "PostElbe快递" },
{ "code": "hermes-de", "name": "德国Hermes快递" },
{ "code": "hermes-uk", "name": "英国Hermes快递" },
{ "code": "tianma", "name": "天马迅达快递" },
{ "code": "apkex", "name": "重点物流 APK Logistics" },
{ "code": "otobv", "name": "中欧快运" },
{ "code": "asiax", "name": "ASIAX快递" },
{ "code": "scorejp", "name": "中国流通王" },
{ "code": "amazon", "name": "亚马逊物流" },
{ "code": "itl", "name": "科捷物流" },
{ "code": "nengda", "name": "能达快递" },
{ "code": "ruifeng", "name": "瑞丰速递" },
{ "code": "suteng", "name": "速腾快递" },
{ "code": "zongxing", "name": "纵行物流" },
{ "code": "jingshi", "name": "京世物流" },
{ "code": "huacheng", "name": "华诚物流" },
{ "code": "11183", "name": "11183快递" }
];